FROM php:7.3.8-cli
COPY . /usr/local/src/myapp
WORKDIR /usr/local/src/myapp
CMD [ "php", "./01-01-notice-for-non-valid-array-container.php" ]
CMD [ "php", "./01-02-get-declared-classes.php" ]
CMD [ "php", "./01-03-fn-reserved-keyword.php" ]
CMD [ "php", "./01-04-list-assignment-by-reference.php" ]